import json
import logging
from datetime import datetime
from typing import List, Dict, Any, Tuple
from fpdf import FPDF

logger = logging.getLogger(__name__)

def generate_report(score: int, gaps: List[Any], improvements: List[Any], preparation: List[Any], keywords: List[Dict[str, Any]], resume_filename: str, jd_snippet: str, elapsed_seconds: float) -> bytes:
    """Generate a PDF report from analysis results."""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "Resume Analysis Report", ln=True, align="C")
    
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 10, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Resume: {resume_filename}", ln=True, align="C")
    pdf.ln(5)
    
    # Score Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "1. Overall Score", ln=True)
    pdf.set_font("helvetica", "B", 24)
    
    if score >= 8:
        pdf.set_text_color(0, 128, 0)
        interp = "Excellent Fit"
    elif score >= 5:
        pdf.set_text_color(255, 165, 0)
        interp = "Good Fit / Needs Improvement"
    else:
        pdf.set_text_color(255, 0, 0)
        interp = "Poor Fit"
        
    pdf.cell(0, 10, f"{score}/10", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "I", 12)
    pdf.cell(0, 10, interp, ln=True)
    pdf.ln(5)
    
    # Keyword Match Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "2. Keyword Match", ln=True)
    pdf.set_font("helvetica", "", 10)
    
    if keywords:
        found_count = sum(1 for kw in keywords if kw.get('found_in_resume'))
        match_pct = (found_count / len(keywords)) * 100
        pdf.cell(0, 10, f"Match Percentage: {match_pct:.1f}%", ln=True)
        
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(80, 10, "Keyword")
        pdf.cell(40, 10, "Category")
        pdf.cell(40, 10, "Status", ln=True)
        
        pdf.set_font("helvetica", "", 10)
        for kw in keywords:
            pdf.cell(80, 10, str(kw.get('keyword', '')).encode('latin-1', 'replace').decode('latin-1'))
            pdf.cell(40, 10, str(kw.get('category', '')).encode('latin-1', 'replace').decode('latin-1'))
            status = "Found" if kw.get('found_in_resume') else "Missing"
            pdf.cell(40, 10, status, ln=True)
    else:
        pdf.cell(0, 10, "No keywords analyzed.", ln=True)
    pdf.ln(5)
    
    # Gap Analysis Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "3. Gap Analysis", ln=True)
    pdf.set_font("helvetica", "", 10)
    
    for i, gap in enumerate(gaps, 1):
        gap_str = str(gap).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 10, f"{i}. {gap_str}")
    pdf.ln(5)
    
    # Improvements Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "4. Recommended Improvements", ln=True)
    pdf.set_font("helvetica", "", 10)
    
    for i, imp in enumerate(improvements, 1):
        imp_str = str(imp).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 10, f"{i}. {imp_str}")
    pdf.ln(5)
    
    # Preparation Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "5. Interview Preparation", ln=True)
    pdf.set_font("helvetica", "", 10)
    
    for i, prep in enumerate(preparation, 1):
        prep_str = str(prep).encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 10, f"{i}. {prep_str}")
    pdf.ln(5)
    
    # Footer
    pdf.set_y(-15)
    pdf.set_font("helvetica", "I", 8)
    pdf.cell(0, 10, f"Generated by Agentic Resume Analyzer | Page {pdf.page_no()}", align="C")
    
    return pdf.output(dest='S')
